### ISSUE TITLE
Compile 32-bit Windows programs

### ISSUE THREAD

**Issue by unitwk** [pmq20/node-packer#70]
I successfully compiled the program.
but it cannot running on 32-bit Windows.
how shoud I compiled with 32-bit windows OS compatible programs...
but it still can only running on 64-bit windows.

please help me,thank you.

My system is Windows10 64-bit ,Vs2017 and Node.js 8.2.0 

@pmq20

**Comment by pmq20** [comment]
To compile to 32-bit windows OS compatible programs on a 64-bit machine, you should use a x64 x32 cross compiling environment. You should be able to find it in your Start Menu after installing Visual Studio. Also, you have to use a 32-bit Node.js, because the arch information is detected via `node -pe process.arch`

**Comment by Suwings** [comment]
I have compiled the 32-bit program successfully.
thanks again.

**Comment by cloverhap** [comment]
Can this be written in the readme or Wiki? This is useful information.

**Comment by pmq20** [comment]
@cloverhap added in https://github.com/pmq20/node-packer/commit/3847bd2ea5f949a8f2de47da8ac2cc10c1ee638d
